# Traefik dynamic configuration for wg-easy HTTPS access
# Generated by scripts/setup-vps.sh — do not edit manually on the server
#
# Placeholders (replaced by sed during setup):
#   __WG_EASY_DOMAIN__  → e.g. vpn.specus.id
#   __DOCKER_HOST_IP__  → Docker bridge gateway (typically 172.17.0.1)

http:
  routers:
    wg-easy:
      rule: "Host(`__WG_EASY_DOMAIN__`)"
      entryPoints:
        - websecure
      service: wg-easy
      tls:
        certResolver: letsencrypt
      middlewares:
        - wg-easy-headers

    wg-easy-http:
      rule: "Host(`__WG_EASY_DOMAIN__`)"
      entryPoints:
        - web
      middlewares:
        - wg-easy-https-redirect
      service: wg-easy

  middlewares:
    wg-easy-https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    wg-easy-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

  services:
    wg-easy:
      loadBalancer:
        servers:
          - url: "http://__DOCKER_HOST_IP__:51821"
